"use client";

import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { FormEvent, useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import {
  ArrowLeft,
  Award,
  CalendarClock,
  CheckCircle2,
  ExternalLink,
  FilePlus2,
  FileText,
  Landmark,
  Plus,
  ShieldCheck,
  Sparkles,
  Trash2,
} from "lucide-react";
import {
  addQuoteDocument,
  addQuoteOffer,
  convertQuote,
  getQuote,
  selectQuoteOffer,
  updateQuoteOffer,
} from "@/services/quotes";
import { getInsurers } from "@/services/insurers";
import { apiError } from "@/lib/api-error";
import type { QuoteOffer } from "@/types/quote";

const euro = (value: number | null | undefined) => value == null ? "-" : new Intl.NumberFormat("pt-PT", { style: "currency", currency: "EUR" }).format(value);
const date = (value: string | null | undefined) => value ? new Date(value).toLocaleDateString("pt-PT") : "-";
const productLabels: Record<string,string> = {AUTO:"Automóvel",MOTORCYCLE:"Moto",HOME:"Habitação",LIFE:"Vida",HEALTH:"Saúde",WORK_ACCIDENT:"Acidentes de Trabalho",BUSINESS:"Empresas",TRAVEL:"Viagem",PERSONAL_ACCIDENT:"Acidentes Pessoais"};
const statusLabels: Record<string,string> = {DRAFT:"Rascunho",QUOTING:"A consultar",COMPARING:"Em comparação",SELECTED:"Proposta escolhida",CONVERTED:"Convertida em apólice",CLOSED:"Encerrada"};

export default function QuoteDetailPage(){
  const params=useParams(); const router=useRouter(); const qc=useQueryClient();
  const id=Number(Array.isArray(params.id)?params.id[0]:params.id);
  const [showOffer,setShowOffer]=useState(false); const [editingOffer,setEditingOffer]=useState<QuoteOffer|null>(null);
  const [showDocument,setShowDocument]=useState(false); const [showConvert,setShowConvert]=useState(false);
  const {data:quote,isPending,isError,error}=useQuery({queryKey:["quote",id],queryFn:()=>getQuote(id),enabled:Number.isInteger(id),retry:false});
  const {data:insurers=[]}=useQuery({queryKey:["insurers"],queryFn:getInsurers});
  const refresh=async()=>{await Promise.all([qc.invalidateQueries({queryKey:["quote",id]}),qc.invalidateQueries({queryKey:["quotes"]}),qc.invalidateQueries({queryKey:["dashboard-v2"]})]);};
  const selectMutation=useMutation({mutationFn:(offerId:number)=>selectQuoteOffer(id,offerId),onSuccess:refresh});
  if(isPending)return <div className="panel p-8 text-slate-400">A carregar cotação…</div>;
  if(isError||!quote)return <div className="rounded-2xl border border-rose-200 bg-rose-50 p-6 text-rose-700">{apiError(error,"Cotação não encontrada.")}</div>;
  const priced=quote.offers.filter(o=>o.annualPremium!=null).sort((a,b)=>(a.annualPremium||0)-(b.annualPremium||0)); const best=priced[0];
  const selected=quote.offers.find(o=>o.selected);
  return <div className="space-y-6">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><button onClick={()=>router.push('/quotes')} className="mb-3 inline-flex items-center gap-1 text-sm font-bold text-cyan-700"><ArrowLeft size={16}/> Cotações</button><div className="flex flex-wrap items-center gap-3"><h1 className="text-3xl font-black tracking-tight">{quote.title}</h1><span className="rounded-xl bg-slate-900 px-3 py-1.5 text-xs font-black text-white">{statusLabels[quote.status]||quote.status}</span></div><p className="mt-2 text-sm text-slate-500">{quote.reference} · {productLabels[quote.productType]||quote.productType} · {quote.client?.name||'Sem cliente'}</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>setShowDocument(true)} className="btn-secondary"><FilePlus2 size={17}/> Documento</button><button onClick={()=>{setEditingOffer(null);setShowOffer(true)}} className="btn-secondary"><Plus size={17}/> Proposta</button>{quote.policy?<Link href={`/policies/${quote.policy.id}`} className="btn-primary"><ShieldCheck size={17}/> Abrir apólice</Link>:<button disabled={!selected} onClick={()=>setShowConvert(true)} className="btn-primary"><Sparkles size={17}/> Converter em apólice</button>}</div></div>

    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi label="Companhias consultadas" value={String(quote.offers.length)} icon={<Landmark/>}/><Kpi label="Propostas recebidas" value={String(priced.length)} icon={<FileText/>}/><Kpi label="Melhor prémio" value={best?euro(best.annualPremium):'A aguardar'} icon={<Award/>}/><Kpi label="Data pretendida" value={date(quote.effectiveDate)} icon={<CalendarClock/>}/></div>

    <section className="panel overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 p-5"><div><p className="eyebrow">Comparação direta</p><h2 className="mt-1 text-xl font-black">Propostas das companhias</h2></div><p className="text-xs text-slate-400">Selecione a proposta aceite pelo cliente antes de criar a apólice.</p></div>
      <div className="overflow-x-auto"><table className="w-full min-w-[920px] text-sm"><thead className="bg-slate-50 text-left text-[10px] font-black uppercase tracking-wider text-slate-400"><tr><th className="p-4">Companhia</th><th className="p-4">Estado</th><th className="p-4">Prémio anual</th><th className="p-4">Fracionado</th><th className="p-4">Franquia</th><th className="p-4">Comissão</th><th className="p-4">Validade</th><th className="p-4 text-right">Ações</th></tr></thead><tbody>{quote.offers.map(offer=><tr key={offer.id} className={`border-t border-slate-100 ${offer.selected?'bg-emerald-50/70':''}`}><td className="p-4"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-slate-900 text-xs font-black text-white">{(offer.insurer.commercialName||offer.insurer.name).slice(0,2).toUpperCase()}</div><div><p className="font-black">{offer.insurer.commercialName||offer.insurer.name}</p><p className="text-xs text-slate-400">{offer.quoteNumber||'Sem nº de simulação'}</p></div></div></td><td className="p-4"><Status value={offer.status}/></td><td className="p-4 text-base font-black text-slate-900">{euro(offer.annualPremium)}</td><td className="p-4">{euro(offer.installmentPremium)}</td><td className="p-4">{euro(offer.deductible)}</td><td className="p-4 font-bold text-emerald-700">{euro(offer.commission)}</td><td className="p-4">{date(offer.validUntil)}</td><td className="p-4"><div className="flex justify-end gap-2"><button onClick={()=>{setEditingOffer(offer);setShowOffer(true)}} className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold hover:bg-slate-50">Editar</button><button disabled={offer.selected||offer.annualPremium==null||selectMutation.isPending} onClick={()=>selectMutation.mutate(offer.id)} className={`rounded-lg px-3 py-2 text-xs font-bold ${offer.selected?'bg-emerald-600 text-white':'bg-slate-900 text-white disabled:opacity-40'}`}>{offer.selected?'Escolhida':'Selecionar'}</button></div></td></tr>)}</tbody></table></div>
      {quote.offers.length===0&&<div className="p-10 text-center text-sm text-slate-500">Adicione companhias e registe as propostas recebidas.</div>}
    </section>

    <div className="grid gap-6 xl:grid-cols-[1.1fr_.9fr]">
      <section className="panel p-5"><p className="eyebrow">Questionário</p><h2 className="mt-1 text-xl font-black">Dados do risco</h2><div className="mt-5 grid gap-3 sm:grid-cols-2">{Object.entries(quote.riskData||{}).map(([key,value])=><Info key={key} label={humanize(key)} value={String(value)}/>)}</div>{Object.keys(quote.riskData||{}).length===0&&<p className="mt-4 text-sm text-slate-500">Sem dados de risco registados.</p>}<div className="mt-5 border-t border-slate-100 pt-5"><p className="text-xs font-black uppercase tracking-wider text-slate-400">Preferências</p><div className="mt-3 flex flex-wrap gap-2">{Object.entries(quote.preferences||{}).map(([key,value])=><span key={key} className="rounded-xl bg-cyan-50 px-3 py-2 text-xs font-bold text-cyan-800">{humanize(key)}: {String(value)}</span>)}</div></div></section>
      <section className="panel p-5"><p className="eyebrow">Histórico</p><h2 className="mt-1 text-xl font-black">Atividade do processo</h2><div className="mt-5 space-y-4">{(quote.activities||[]).map(activity=><div key={activity.id} className="flex gap-3"><div className="mt-1 h-3 w-3 shrink-0 rounded-full bg-cyan-500 ring-4 ring-cyan-50"/><div><p className="text-sm font-bold">{activity.description||activity.action}</p><p className="mt-1 text-xs text-slate-400">{new Date(activity.createdAt).toLocaleString('pt-PT')}</p></div></div>)}</div></section>
    </div>

    <section className="panel p-5"><div className="flex items-center justify-between"><div><p className="eyebrow">Dossier</p><h2 className="mt-1 text-xl font-black">Documentação</h2></div><button onClick={()=>setShowDocument(true)} className="btn-secondary"><FilePlus2 size={16}/> Adicionar</button></div><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{(quote.documents||[]).map(doc=><div key={doc.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex items-start justify-between"><div className="rounded-xl bg-blue-50 p-2 text-blue-600"><FileText size={20}/></div>{doc.url&&<a href={doc.url} target="_blank" rel="noreferrer" className="text-slate-400 hover:text-cyan-600"><ExternalLink size={17}/></a>}</div><p className="mt-3 font-black">{doc.name}</p><p className="mt-1 text-xs text-slate-400">{doc.type} · {date(doc.createdAt)}</p></div>)}</div>{(quote.documents||[]).length===0&&<p className="mt-4 text-sm text-slate-500">Sem documentos associados.</p>}</section>

    {showOffer&&<OfferModal quoteId={id} insurers={insurers} offer={editingOffer} onClose={()=>setShowOffer(false)} onSaved={async()=>{setShowOffer(false);await refresh()}}/>}
    {showDocument&&<DocumentModal quoteId={id} onClose={()=>setShowDocument(false)} onSaved={async()=>{setShowDocument(false);await refresh()}}/>}
    {showConvert&&selected&&<ConvertModal quoteId={id} offer={selected} onClose={()=>setShowConvert(false)} onSaved={async(policyId)=>{await refresh();router.push(`/policies/${policyId}`)}}/>}
  </div>;
}

function Kpi({label,value,icon}:{label:string;value:string;icon:React.ReactNode}){return <div className="panel flex items-center gap-4 p-5"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-cyan-50 text-cyan-700">{icon}</div><div><p className="text-xs font-bold text-slate-400">{label}</p><p className="mt-1 text-xl font-black">{value}</p></div></div>}
function Status({value}:{value:string}){const styles:valueStyles=({REQUESTED:'bg-amber-50 text-amber-700',RECEIVED:'bg-blue-50 text-blue-700',ACCEPTED:'bg-emerald-50 text-emerald-700',DECLINED:'bg-rose-50 text-rose-700'} as any);return <span className={`rounded-lg px-2 py-1 text-[10px] font-black uppercase ${styles[value]||'bg-slate-100 text-slate-600'}`}>{value}</span>}
type valueStyles=Record<string,string>;
function Info({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-slate-50 p-3"><p className="text-[10px] font-black uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1 text-sm font-bold text-slate-800">{value}</p></div>}
function humanize(value:string){return value.replace(/([A-Z])/g,' $1').replace(/^./,m=>m.toUpperCase())}

function OfferModal({quoteId,insurers,offer,onClose,onSaved}:{quoteId:number;insurers:any[];offer:QuoteOffer|null;onClose:()=>void;onSaved:()=>void}){
  const [form,setForm]=useState({insurerId:String(offer?.insurerId||''),quoteNumber:offer?.quoteNumber||'',annualPremium:String(offer?.annualPremium??''),installmentPremium:String(offer?.installmentPremium??''),commission:String(offer?.commission??''),deductible:String(offer?.deductible??''),validUntil:offer?.validUntil?.slice(0,10)||'',status:offer?.status||'RECEIVED',coverages:offer?.coverages?Object.entries(offer.coverages).map(([k,v])=>`${humanize(k)}: ${v}`).join('\n'):'',notes:offer?.notes||''});
  const mutation=useMutation({mutationFn:()=>{const coverages=Object.fromEntries(form.coverages.split('\n').map(line=>line.split(':')).filter(parts=>parts[0]?.trim()).map(([k,...v])=>[k.trim(),v.join(':').trim()||true]));const data={insurerId:Number(form.insurerId),quoteNumber:form.quoteNumber||null,annualPremium:form.annualPremium?Number(form.annualPremium):null,installmentPremium:form.installmentPremium?Number(form.installmentPremium):null,commission:form.commission?Number(form.commission):null,deductible:form.deductible?Number(form.deductible):null,validUntil:form.validUntil||null,status:form.status,coverages,notes:form.notes||null};return offer?updateQuoteOffer(offer.id,data):addQuoteOffer(quoteId,data)},onSuccess:onSaved});
  return <Modal title={offer?'Editar proposta':'Adicionar proposta'} onClose={onClose}><form onSubmit={(e)=>{e.preventDefault();mutation.mutate()}} className="grid gap-4 md:grid-cols-2"><Field label="Companhia"><select required className="field" value={form.insurerId} onChange={(e)=>setForm({...form,insurerId:e.target.value})}><option value="">Escolher…</option>{insurers.map(i=><option key={i.id} value={i.id}>{i.commercialName||i.name}</option>)}</select></Field><Field label="N.º simulação"><input className="field" value={form.quoteNumber} onChange={(e)=>setForm({...form,quoteNumber:e.target.value})}/></Field><Field label="Prémio anual"><input type="number" step="0.01" className="field" value={form.annualPremium} onChange={(e)=>setForm({...form,annualPremium:e.target.value})}/></Field><Field label="Prémio fracionado"><input type="number" step="0.01" className="field" value={form.installmentPremium} onChange={(e)=>setForm({...form,installmentPremium:e.target.value})}/></Field><Field label="Franquia"><input type="number" step="0.01" className="field" value={form.deductible} onChange={(e)=>setForm({...form,deductible:e.target.value})}/></Field><Field label="Comissão"><input type="number" step="0.01" className="field" value={form.commission} onChange={(e)=>setForm({...form,commission:e.target.value})}/></Field><Field label="Validade"><input type="date" className="field" value={form.validUntil} onChange={(e)=>setForm({...form,validUntil:e.target.value})}/></Field><Field label="Estado"><select className="field" value={form.status} onChange={(e)=>setForm({...form,status:e.target.value})}><option value="REQUESTED">Solicitada</option><option value="RECEIVED">Recebida</option><option value="DECLINED">Recusada</option><option value="ACCEPTED">Aceite</option></select></Field><div className="md:col-span-2"><Field label="Coberturas (uma por linha: Nome: valor)"><textarea rows={5} className="field resize-none" value={form.coverages} onChange={(e)=>setForm({...form,coverages:e.target.value})}/></Field></div><div className="md:col-span-2"><Field label="Notas"><textarea rows={3} className="field resize-none" value={form.notes} onChange={(e)=>setForm({...form,notes:e.target.value})}/></Field></div>{mutation.isError&&<p className="md:col-span-2 text-sm font-bold text-rose-600">{apiError(mutation.error)}</p>}<div className="md:col-span-2 flex justify-end gap-2"><button type="button" onClick={onClose} className="btn-secondary">Cancelar</button><button disabled={mutation.isPending} className="btn-primary">Guardar proposta</button></div></form></Modal>;
}

function DocumentModal({quoteId,onClose,onSaved}:{quoteId:number;onClose:()=>void;onSaved:()=>void}){const[form,setForm]=useState({name:'',type:'PROPOSAL',url:'',notes:''});const mutation=useMutation({mutationFn:()=>addQuoteDocument(quoteId,form),onSuccess:onSaved});return <Modal title="Adicionar documento" onClose={onClose}><form onSubmit={(e)=>{e.preventDefault();mutation.mutate()}} className="space-y-4"><Field label="Nome"><input required className="field" value={form.name} onChange={(e)=>setForm({...form,name:e.target.value})}/></Field><Field label="Tipo"><select className="field" value={form.type} onChange={(e)=>setForm({...form,type:e.target.value})}><option value="PROPOSAL">Proposta</option><option value="QUESTIONNAIRE">Questionário</option><option value="IDENTIFICATION">Identificação</option><option value="OTHER">Outro</option></select></Field><Field label="Ligação para ficheiro"><input type="url" className="field" placeholder="https://…" value={form.url} onChange={(e)=>setForm({...form,url:e.target.value})}/></Field><Field label="Notas"><textarea className="field resize-none" rows={3} value={form.notes} onChange={(e)=>setForm({...form,notes:e.target.value})}/></Field><div className="flex justify-end gap-2"><button type="button" onClick={onClose} className="btn-secondary">Cancelar</button><button className="btn-primary">Adicionar</button></div></form></Modal>}

function ConvertModal({quoteId,offer,onClose,onSaved}:{quoteId:number;offer:QuoteOffer;onClose:()=>void;onSaved:(id:number)=>void}){const[form,setForm]=useState({policyNumber:'',proposalNumber:offer.quoteNumber||'',startDate:new Date().toISOString().slice(0,10),renewalDate:new Date(Date.now()+365*86400000).toISOString().slice(0,10),paymentFrequency:'ANNUAL',notes:''});const mutation=useMutation({mutationFn:()=>convertQuote(quoteId,form),onSuccess:(p)=>onSaved(p.id)});return <Modal title="Converter em apólice" onClose={onClose}><div className="mb-4 rounded-2xl bg-emerald-50 p-4"><p className="text-xs font-black uppercase text-emerald-700">Proposta selecionada</p><p className="mt-1 font-black">{offer.insurer.commercialName||offer.insurer.name} · {euro(offer.annualPremium)}</p></div><form onSubmit={(e)=>{e.preventDefault();mutation.mutate()}} className="grid gap-4 md:grid-cols-2"><Field label="Número da apólice *"><input required className="field" value={form.policyNumber} onChange={(e)=>setForm({...form,policyNumber:e.target.value})}/></Field><Field label="Número da proposta"><input className="field" value={form.proposalNumber} onChange={(e)=>setForm({...form,proposalNumber:e.target.value})}/></Field><Field label="Data de início"><input type="date" className="field" value={form.startDate} onChange={(e)=>setForm({...form,startDate:e.target.value})}/></Field><Field label="Próxima renovação"><input type="date" className="field" value={form.renewalDate} onChange={(e)=>setForm({...form,renewalDate:e.target.value})}/></Field><Field label="Periodicidade"><select className="field" value={form.paymentFrequency} onChange={(e)=>setForm({...form,paymentFrequency:e.target.value})}><option value="MONTHLY">Mensal</option><option value="QUARTERLY">Trimestral</option><option value="SEMIANNUAL">Semestral</option><option value="ANNUAL">Anual</option><option value="SINGLE">Única</option></select></Field><div className="md:col-span-2"><Field label="Notas"><textarea rows={3} className="field resize-none" value={form.notes} onChange={(e)=>setForm({...form,notes:e.target.value})}/></Field></div>{mutation.isError&&<p className="md:col-span-2 text-sm font-bold text-rose-600">{apiError(mutation.error)}</p>}<div className="md:col-span-2 flex justify-end gap-2"><button type="button" onClick={onClose} className="btn-secondary">Cancelar</button><button disabled={mutation.isPending} className="btn-primary"><ShieldCheck size={17}/>{mutation.isPending?'A criar…':'Criar apólice'}</button></div></form></Modal>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/55 p-4 backdrop-blur-sm" onMouseDown={onClose}><div onMouseDown={(e)=>e.stopPropagation()} className="max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-3xl bg-white p-6 shadow-2xl"><div className="mb-5 flex items-center justify-between"><h2 className="text-xl font-black">{title}</h2><button onClick={onClose} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100">×</button></div>{children}</div></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-2 block text-sm font-bold text-slate-700">{label}</span>{children}</label>}
