"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { FormEvent, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, CalendarClock, ExternalLink, FilePlus2, FileText, ShieldCheck, User, Building2, Sparkles } from "lucide-react";
import { addPolicyDocument, getPolicy } from "@/services/policies";
import { apiError } from "@/lib/api-error";

const euro=(value:number|null)=>value==null?'-':new Intl.NumberFormat('pt-PT',{style:'currency',currency:'EUR'}).format(value);
const date=(value:string|null)=>value?new Date(value).toLocaleDateString('pt-PT'):'-';

export default function PolicyDetailPage(){const params=useParams();const id=Number(Array.isArray(params.id)?params.id[0]:params.id);const qc=useQueryClient();const[showDoc,setShowDoc]=useState(false);const{data:p,isPending,isError,error}=useQuery({queryKey:['policy',id],queryFn:()=>getPolicy(id),enabled:Number.isInteger(id),retry:false});if(isPending)return <div className="panel p-8 text-slate-400">A carregar apólice…</div>;if(isError||!p)return <div className="rounded-2xl border border-rose-200 bg-rose-50 p-6 text-rose-700">{apiError(error,'Apólice não encontrada.')}</div>;
return <div className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><Link href="/policies" className="mb-3 inline-flex items-center gap-1 text-sm font-bold text-cyan-700"><ArrowLeft size={16}/> Apólices</Link><div className="flex items-center gap-3"><h1 className="text-3xl font-black">{p.policyNumber}</h1><span className="rounded-xl bg-emerald-50 px-3 py-1.5 text-xs font-black text-emerald-700">{p.status}</span></div><p className="mt-2 text-sm text-slate-500">{p.product} · {p.branch||'Ramo não definido'}</p></div><div className="flex gap-2"><button onClick={()=>setShowDoc(true)} className="btn-secondary"><FilePlus2 size={17}/> Documento</button>{p.quote&&<Link href={`/quotes/${p.quote.id}`} className="btn-primary"><Sparkles size={17}/> Ver cotação de origem</Link>}</div></div>
<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Card icon={<User/>} label="Tomador" value={p.client?.name||'-'} href={p.client?`/clients/${p.client.id}`:undefined}/><Card icon={<Building2/>} label="Companhia" value={p.insurer?.commercialName||p.insurerNameLegacy||'-'} href={p.insurer?`/insurers/${p.insurer.id}`:undefined}/><Card icon={<ShieldCheck/>} label="Prémio" value={euro(p.premium)}/><Card icon={<CalendarClock/>} label="Próxima renovação" value={date(p.renewalDate)}/></div>
<div className="grid gap-6 xl:grid-cols-[1.05fr_.95fr]"><section className="panel p-5"><p className="eyebrow">Dados contratuais</p><h2 className="mt-1 text-xl font-black">Informação da apólice</h2><div className="mt-5 grid gap-3 sm:grid-cols-2"><Info label="N.º proposta" value={p.proposalNumber}/><Info label="Início" value={date(p.startDate)}/><Info label="Periodicidade" value={p.paymentFrequency}/><Info label="Comissão" value={euro(p.commission)}/><Info label="Criada em" value={date(p.createdAt)}/><Info label="Atualizada em" value={date(p.updatedAt)}/></div><div className="mt-5 rounded-xl bg-slate-50 p-4"><p className="text-[10px] font-black uppercase tracking-wider text-slate-400">Observações</p><p className="mt-2 whitespace-pre-wrap text-sm text-slate-700">{p.notes||'Sem observações.'}</p></div></section>
<section className="panel p-5"><p className="eyebrow">Companhia</p><h2 className="mt-1 text-xl font-black">Apoio ao mediador</h2><div className="mt-5 space-y-3">{(p.insurer?.contacts||[]).length===0?<p className="text-sm text-slate-500">Contactos ainda não configurados.</p>:(p.insurer.contacts||[]).map((c:any)=><div key={c.id} className="rounded-xl border border-slate-100 p-3"><p className="text-xs font-black text-cyan-700">{c.type}</p><p className="mt-1 font-bold">{c.name||c.department||'Contacto'}</p><p className="mt-1 text-xs text-slate-500">{c.phone||c.mobile||'-'} · {c.email||'-'}</p></div>)}</div></section></div>
<section className="panel p-5"><div className="flex items-center justify-between"><div><p className="eyebrow">Dossier</p><h2 className="mt-1 text-xl font-black">Documentação</h2></div><button onClick={()=>setShowDoc(true)} className="btn-secondary"><FilePlus2 size={16}/> Adicionar</button></div><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{(p.documents||[]).map((doc:any)=><div key={doc.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex items-start justify-between"><div className="rounded-xl bg-blue-50 p-2 text-blue-600"><FileText size={20}/></div>{doc.url&&<a href={doc.url} target="_blank" rel="noreferrer" className="text-slate-400 hover:text-cyan-600"><ExternalLink size={17}/></a>}</div><p className="mt-3 font-black">{doc.name}</p><p className="mt-1 text-xs text-slate-400">{doc.type} · {date(doc.createdAt)}</p></div>)}</div>{(p.documents||[]).length===0&&<p className="mt-4 text-sm text-slate-500">Sem documentos associados.</p>}</section>
<section className="panel p-5"><p className="eyebrow">Ocorrências</p><h2 className="mt-1 text-xl font-black">Sinistros associados</h2><div className="mt-5 space-y-3">{(p.claims||[]).map((claim:any)=><div key={claim.id} className="flex items-center justify-between rounded-xl border border-slate-100 p-4"><div><p className="font-black">{claim.claimNumber}</p><p className="mt-1 text-sm text-slate-500">{claim.description||'Sem descrição'}</p></div><span className="rounded-lg bg-amber-50 px-2 py-1 text-xs font-bold text-amber-700">{claim.status}</span></div>)}{(p.claims||[]).length===0&&<p className="text-sm text-slate-500">Sem sinistros registados.</p>}</div></section>
{showDoc&&<DocumentModal policyId={id} onClose={()=>setShowDoc(false)} onSaved={async()=>{setShowDoc(false);await qc.invalidateQueries({queryKey:['policy',id]})}}/>}</div>}
function Card({icon,label,value,href}:{icon:React.ReactNode;label:string;value:string;href?:string}){const content=<><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-cyan-50 text-cyan-700">{icon}</div><div className="min-w-0"><p className="text-xs font-bold text-slate-400">{label}</p><p className="mt-1 truncate text-lg font-black">{value}</p></div></>;return href?<Link href={href} className="panel flex items-center gap-4 p-5 transition hover:-translate-y-0.5">{content}</Link>:<div className="panel flex items-center gap-4 p-5">{content}</div>}
function Info({label,value}:{label:string;value:string|null}){return <div className="rounded-xl bg-slate-50 p-3"><p className="text-[10px] font-black uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1 text-sm font-bold">{value||'-'}</p></div>}
function DocumentModal({policyId,onClose,onSaved}:{policyId:number;onClose:()=>void;onSaved:()=>void}){const[form,setForm]=useState({name:'',type:'POLICY',url:'',notes:''});const mutation=useMutation({mutationFn:()=>addPolicyDocument(policyId,form),onSuccess:onSaved});function submit(e:FormEvent){e.preventDefault();mutation.mutate()}return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/55 p-4 backdrop-blur-sm" onMouseDown={onClose}><form onSubmit={submit} onMouseDown={(e)=>e.stopPropagation()} className="w-full max-w-xl rounded-3xl bg-white p-6 shadow-2xl"><h2 className="text-xl font-black">Adicionar documento</h2><div className="mt-5 space-y-4"><label className="block text-sm font-bold">Nome<input required className="field mt-2" value={form.name} onChange={(e)=>setForm({...form,name:e.target.value})}/></label><label className="block text-sm font-bold">Tipo<select className="field mt-2" value={form.type} onChange={(e)=>setForm({...form,type:e.target.value})}><option value="POLICY">Condições / apólice</option><option value="RECEIPT">Recibo</option><option value="CERTIFICATE">Certificado</option><option value="OTHER">Outro</option></select></label><label className="block text-sm font-bold">URL do documento<input type="url" className="field mt-2" value={form.url} onChange={(e)=>setForm({...form,url:e.target.value})}/></label><label className="block text-sm font-bold">Notas<textarea rows={3} className="field mt-2 resize-none" value={form.notes} onChange={(e)=>setForm({...form,notes:e.target.value})}/></label>{mutation.isError&&<p className="text-sm font-bold text-rose-600">{apiError(mutation.error)}</p>}<div className="flex justify-end gap-2"><button type="button" onClick={onClose} className="btn-secondary">Cancelar</button><button className="btn-primary">Adicionar</button></div></div></form></div>}
