export const PERMISSIONS = {
  PLATFORM_MANAGE: "platform.manage",
  ORGANIZATION_MANAGE: "organization.manage",
  USERS_MANAGE: "users.manage",
  INTEGRATIONS_MANAGE: "integrations.manage",
  PORTFOLIO_IMPORT: "portfolio.import",
  AUDIT_READ: "audit.read",
  DASHBOARD_FINANCIALS: "dashboard.financials",
  CLIENTS_READ: "clients.read",
  CLIENTS_WRITE: "clients.write",
  CLIENTS_DELETE: "clients.delete",
  QUOTES_READ: "quotes.read",
  QUOTES_WRITE: "quotes.write",
  QUOTES_CONVERT: "quotes.convert",
  POLICIES_READ: "policies.read",
  POLICIES_WRITE: "policies.write",
  POLICIES_DELETE: "policies.delete",
  CLAIMS_MANAGE: "claims.manage",
  CALENDAR_MANAGE: "calendar.manage",
  EXPORT_DATA: "data.export",
  VIEW_ALL_PROCESSES: "processes.view_all",
} as const;

export const PERMISSION_OPTIONS = [
  { code: PERMISSIONS.DASHBOARD_FINANCIALS, label: "Ver prémios, comissões e totais da carteira" },
  { code: PERMISSIONS.USERS_MANAGE, label: "Gerir utilizadores e permissões" },
  { code: PERMISSIONS.INTEGRATIONS_MANAGE, label: "Gerir APIs e credenciais das companhias" },
  { code: PERMISSIONS.PORTFOLIO_IMPORT, label: "Importar carteira por API, webservice ou ficheiro" },
  { code: PERMISSIONS.AUDIT_READ, label: "Consultar registo de auditoria" },
  { code: PERMISSIONS.CLIENTS_DELETE, label: "Eliminar clientes" },
  { code: PERMISSIONS.QUOTES_CONVERT, label: "Converter cotações em apólices" },
  { code: PERMISSIONS.POLICIES_WRITE, label: "Alterar apólices e documentos" },
  { code: PERMISSIONS.POLICIES_DELETE, label: "Eliminar apólices" },
  { code: PERMISSIONS.EXPORT_DATA, label: "Exportar dados" },
  { code: PERMISSIONS.VIEW_ALL_PROCESSES, label: "Ver processos de toda a equipa" },
];
