"use client";

import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, Building2, FileCheck2, Mail, MapPin, Phone, Sparkles, UserRound } from "lucide-react";
import { deleteClient, getApiErrorMessage, getClient, updateClient } from "@/services/clients";

const euro=(v:number|null)=>v==null?'-':new Intl.NumberFormat('pt-PT',{style:'currency',currency:'EUR'}).format(v);
const date=(v:string|null)=>v?new Date(v).toLocaleDateString('pt-PT'):'-';

export default function ClientDetailsPage(){
  const params=useParams();const router=useRouter();const qc=useQueryClient();const id=Number(Array.isArray(params.id)?params.id[0]:params.id);
  const{data:client,isPending,isError,error}=useQuery({queryKey:['client',id],queryFn:()=>getClient(id),enabled:Number.isInteger(id),retry:false});
  const statusMutation=useMutation({mutationFn:(active:boolean)=>updateClient(id,{active}),onSuccess:async()=>{await Promise.all([qc.invalidateQueries({queryKey:['client',id]}),qc.invalidateQueries({queryKey:['clients']})])}});
  const deleteMutation=useMutation({mutationFn:()=>deleteClient(id),onSuccess:async()=>{await qc.invalidateQueries({queryKey:['clients']});router.push('/clients')}});
  if(isPending)return <div className="panel p-8 text-slate-400">A carregar cliente…</div>;
  if(isError||!client)return <div className="rounded-2xl border border-rose-200 bg-rose-50 p-6 text-rose-700">{getApiErrorMessage(error,'Cliente não encontrado.')}</div>;
  const mutationError=statusMutation.error||deleteMutation.error;
  return <div className="space-y-6">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><Link href="/clients" className="mb-3 inline-flex items-center gap-1 text-sm font-bold text-cyan-700"><ArrowLeft size={16}/> Clientes</Link><div className="flex flex-wrap items-center gap-3"><h1 className="text-3xl font-black">{client.name}</h1><span className={`rounded-xl px-3 py-1.5 text-xs font-black ${client.active?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-500'}`}>{client.active?'Ativo':'Inativo'}</span><span className="rounded-xl bg-blue-50 px-3 py-1.5 text-xs font-black text-blue-700">{client.type==='BUSINESS'?'Empresa':'Particular'}</span></div><p className="mt-2 text-sm text-slate-500">NIF {client.nif||'não indicado'} · cliente desde {date(client.createdAt)}</p></div><div className="flex flex-wrap gap-2"><Link href={`/quotes/new?clientId=${client.id}`} className="btn-primary"><Sparkles size={17}/> Nova cotação</Link><Link href={`/clients/${client.id}/edit`} className="btn-secondary">Editar</Link><button onClick={()=>statusMutation.mutate(!client.active)} className="btn-secondary">{client.active?'Desativar':'Ativar'}</button><button onClick={()=>{if(confirm(`Eliminar ${client.name}?`))deleteMutation.mutate()}} className="rounded-xl bg-rose-600 px-4 py-2.5 text-sm font-bold text-white">Eliminar</button></div></div>
    {mutationError&&<div className="rounded-2xl border border-rose-200 bg-rose-50 p-4 text-rose-700">{getApiErrorMessage(mutationError)}</div>}
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Card icon={<UserRound/>} label={client.type==='BUSINESS'?'Representante':'Data de nascimento'} value={client.type==='BUSINESS'?(client.representativeName||'-'):date(client.birthDate)}/><Card icon={<Mail/>} label="Email" value={client.email||'-'}/><Card icon={<Phone/>} label="Telefone" value={client.phone||'-'}/><Card icon={<MapPin/>} label="Localidade" value={[client.postalCode,client.city].filter(Boolean).join(' ')||'-'}/></div>
    <div className="grid gap-6 xl:grid-cols-[.8fr_1.2fr]"><section className="panel p-5"><p className="eyebrow">Ficha</p><h2 className="mt-1 text-xl font-black">Dados do cliente</h2><div className="mt-5 grid gap-3 sm:grid-cols-2"><Info label="Nome" value={client.name}/><Info label="NIF" value={client.nif}/><Info label="CAE" value={client.cae}/><Info label="País" value={client.country}/><Info label="Morada" value={client.address}/><Info label="Constituição" value={date(client.incorporationDate)}/></div><div className="mt-5 rounded-xl bg-slate-50 p-4"><p className="text-[10px] font-black uppercase tracking-wider text-slate-400">Observações</p><p className="mt-2 whitespace-pre-wrap text-sm text-slate-700">{client.notes||'Sem observações.'}</p></div></section>
    <section className="panel overflow-hidden"><div className="flex items-center justify-between border-b border-slate-100 p-5"><div><p className="eyebrow">Pipeline</p><h2 className="mt-1 text-xl font-black">Cotações</h2></div><Link href="/quotes/new" className="text-sm font-bold text-cyan-700">+ Nova cotação</Link></div><div className="divide-y divide-slate-100">{(client.quotes||[]).map(q=>{const priced=q.offers.filter(o=>o.annualPremium!=null).sort((a,b)=>(a.annualPremium||0)-(b.annualPremium||0));return <Link key={q.id} href={`/quotes/${q.id}`} className="flex items-center justify-between gap-4 p-4 hover:bg-slate-50"><div><p className="text-xs font-bold text-cyan-700">{q.reference} · {q.productType}</p><p className="mt-1 font-black">{q.title}</p><p className="mt-1 text-xs text-slate-400">{q.offers.length} companhias · {q.status}</p></div><div className="text-right"><p className="text-xs text-slate-400">Melhor proposta</p><p className="font-black">{priced[0]?euro(priced[0].annualPremium):'A aguardar'}</p></div></Link>})}{(client.quotes||[]).length===0&&<p className="p-8 text-sm text-slate-500">Sem cotações registadas.</p>}</div></section></div>
    <section className="panel overflow-hidden"><div className="flex items-center justify-between border-b border-slate-100 p-5"><div><p className="eyebrow">Carteira</p><h2 className="mt-1 text-xl font-black">Apólices</h2></div><span className="rounded-xl bg-slate-100 px-3 py-1 text-xs font-black">{client.policies?.length||0}</span></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-[10px] font-black uppercase tracking-wider text-slate-400"><tr><th className="p-4">Apólice</th><th className="p-4">Produto</th><th className="p-4">Companhia</th><th className="p-4">Prémio</th><th className="p-4">Renovação</th><th className="p-4">Estado</th></tr></thead><tbody>{(client.policies||[]).map(p=><tr key={p.id} className="border-t border-slate-100"><td className="p-4"><Link href={`/policies/${p.id}`} className="font-black text-cyan-700">{p.policyNumber}</Link></td><td className="p-4">{p.product}</td><td className="p-4">{p.insurer?.commercialName||p.insurerNameLegacy||'-'}</td><td className="p-4 font-black">{euro(p.premium)}</td><td className="p-4">{date(p.renewalDate)}</td><td className="p-4">{p.status}</td></tr>)}</tbody></table></div>{(client.policies||[]).length===0&&<p className="p-8 text-sm text-slate-500">Este cliente ainda não tem apólices.</p>}</section>
    <div className="grid gap-6 xl:grid-cols-2"><section className="panel p-5"><p className="eyebrow">Ocorrências</p><h2 className="mt-1 text-xl font-black">Sinistros</h2><div className="mt-4 space-y-3">{(client.claims||[]).map(c=><div key={c.id} className="rounded-xl border border-slate-100 p-4"><div className="flex justify-between"><p className="font-black">{c.claimNumber}</p><span className="text-xs font-bold text-amber-700">{c.status}</span></div><p className="mt-2 text-sm text-slate-500">{c.description||'Sem descrição.'}</p></div>)}{(client.claims||[]).length===0&&<p className="text-sm text-slate-500">Sem sinistros registados.</p>}</div></section><section className="panel p-5"><p className="eyebrow">Oportunidades</p><h2 className="mt-1 text-xl font-black">Venda cruzada</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><Suggestion title="Saúde"/><Suggestion title="Vida"/><Suggestion title="Habitação"/><Suggestion title="Acidentes Pessoais"/></div></section></div>
  </div>}
function Card({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="panel flex items-center gap-4 p-5"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-cyan-50 text-cyan-700">{icon}</div><div className="min-w-0"><p className="text-xs font-bold text-slate-400">{label}</p><p className="mt-1 truncate font-black">{value}</p></div></div>}
function Info({label,value}:{label:string;value:string|null}){return <div className="rounded-xl bg-slate-50 p-3"><p className="text-[10px] font-black uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1 text-sm font-bold">{value||'-'}</p></div>}
function Suggestion({title}:{title:string}){return <Link href="/quotes/new" className="flex items-center gap-3 rounded-xl border border-slate-100 p-3 transition hover:border-cyan-300 hover:bg-cyan-50"><Building2 size={17} className="text-cyan-600"/><span className="text-sm font-bold">Simular {title}</span></Link>}
